### ISSUE TITLE
Installation failed Issue

### ISSUE THREAD

**Issue by IReDaRX** [cyber-meow/anime_screenshot_pipeline#53]
I've been trying to install this pipeline and I ran into this issue: 
Installing torch
'C:\AnimeScreenshot' is not recognized as an internal or external command,
operable program or batch file.
Error running command: C:\AnimeScreenshot pipeline\anime_screenshot_pipeline\venv\Scripts\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
Error code: 1
ERROR: Installation failed. Please check the error messages above.
```
Microsoft Windows [Version 10.0.22000.2538]
(c) Microsoft Corporation. All rights reserved.

C:\AnimeScreenshot pipeline>git clone https://github.com/cyber-meow/anime_screenshot_pipeline
Cloning into 'anime_screenshot_pipeline'...
remote: Enumerating objects: 1701, done.
remote: Counting objects: 100% (596/596), done.
remote: Compressing objects: 100% (251/251), done.
remote: Total 1701 (delta 387), reused 537 (delta 344), pack-reused 1105
Receiving objects: 100% (1701/1701), 5.09 MiB | 11.47 MiB/s, done.
Resolving deltas: 100% (1060/1060), done.

C:\AnimeScreenshot pipeline>cd anime_screenshot_pipeline

C:\AnimeScreenshot pipeline\anime_screenshot_pipeline>install.bat
****************************************************************
Python Environment Setup Script
****************************************************************
Updating Git submodules...
Submodule 'waifuc' (https://github.com/deepghs/waifuc) registered for path 'waifuc'
Cloning into 'C:/AnimeScreenshot pipeline/anime_screenshot_pipeline/waifuc'...
Submodule path 'waifuc': checked out '87cc9f6b389729b688abe92c7016a86a35d1e0e3'

Select environment setup:
1) venv
2) conda
3) existing environment
Enter choice [1-3]: 1
****************************************************************
Environment setup complete.
****************************************************************
Installing torch
'C:\AnimeScreenshot' is not recognized as an internal or external command,
operable program or batch file.
Error running command: C:\AnimeScreenshot pipeline\anime_screenshot_pipeline\venv\Scripts\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
Error code: 1
ERROR: Installation failed. Please check the error messages above.

C:\AnimeScreenshot pipeline\anime_screenshot_pipeline>
```

**Comment by cyber-meow** [comment]
Hi,
I think I did not take care of white space properly in my installation script. Could you replace the folder name `AnimeScreenshot pipeline` by `AnimeScreenshot_pipeline`? This should solve the problem.

**Comment by IReDaRX** [comment]
> Hi, I think I did not take care of white space properly in my installation script. Could you replace the folder name `AnimeScreenshot pipeline` by `AnimeScreenshot_pipeline`? This should solve the problem.

Yep, that solved the problem. Thanks!

**Comment by IReDaRX** [comment]
> Hi, I think I did not take care of white space properly in my installation script. Could you replace the folder name `AnimeScreenshot pipeline` by `AnimeScreenshot_pipeline`? This should solve the problem.

I am encountering this error message:

```
>  62%|██████████████████████████████████████████████████▍                               | 16/26 [00:34<00:21,  2.14s/it]
Traceback (most recent call last):
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\automatic_pipeline.py", line 685, in <module>
    asyncio.run(main(configs))
  File "C:\Users\kirito\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\kirito\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\automatic_pipeline.py", line 637, in main
    await asyncio.gather(
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\automatic_pipeline.py", line 614, in run_pipeline
    await loop.run_in_executor(executor, run_stage, config, stage_num, logger)
  File "C:\Users\kirito\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\automatic_pipeline.py", line 550, in run_stage
    STAGE_FUNCTIONS[stage_num](config, stage_num, logger)
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\automatic_pipeline.py", line 203, in extract_frames_and_or_remove_similar
    extract_and_remove_similar(
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\anime2sd\extract_frames.py", line 130, in extract_and_remove_similar
    duplicate_remover.remove_similar_from_dir(dst_ep_dir)
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\anime2sd\remove_duplicates.py", line 281, in remove_similar_from_dir
    self.remove_similar(dataset)
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\anime2sd\remove_duplicates.py", line 236, in remove_similar
    embeddings = self.compute_embeddings(dataset)
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\anime2sd\remove_duplicates.py", line 187, in compute_embeddings
    for _, images in tqdm(dataloader):
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\torch\_utils.py", line 705, in reraise
    raise exception
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\anime2sd\remove_duplicates.py", line 42, in __getitem__
    image = Image.open(image_path).convert("RGB")
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\PIL\Image.py", line 916, in convert
    self.load()
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\PIL\ImageFile.py", line 288, in load
    raise_oserror(err_code)
  File "C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline\venv\lib\site-packages\PIL\ImageFile.py", line 72, in raise_oserror
    raise OSError(msg)
OSError: broken data stream when reading image file


(venv) C:\AnimeScreenshot_pipeline\anime_screenshot_pipeline>
```

**Comment by cyber-meow** [comment]
Hi,
I think this means that some image is corrupted and PIL fails to open it. What is weird is that seems to happen to extracted image as you are only at the very first stage. Can you check the images in your image folder, and maybe verify with a small script that just open them using Image.open from PIL?
